### ISSUE TITLE
Fix issue that caused rollback https://github.com/LLK/scratch-gui/pull/5002

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#866]
SVG-renderer change exposed a bug that crashes paint

**Comment by fsih** [comment]
Repro by going to http://localhost:8601/#167167477 with scratch-svg-renderer dependency     "scratch-svg-renderer": "0.2.0-prerelease.20190715153806" in GUI

**Comment by fsih** [comment]
gui Unhandled Error: Error: TypeError: child.getAttribute is not a function    at onError (http://localhost:8601/lib.min.js:15285:11)    at onLoad (http://localhost:8601/lib.min.js:15276:5)    at importSVG (http://localhost:8601/lib.min.js:15311:4)    at Project.importSVG (http://localhost:8601/lib.min.js:15326:11)    at PaperCanvas.importSvg (http://localhost:8601/lib.min.js:203903:69)    at PaperCanvas.wrapper [as importSvg] (http://localhost:8601/lib.min.js:89274:15)    at PaperCanvas.importImage (http://localhost:8601/lib.min.js:203855:14)    at PaperCanvas.switchCostume (http://localhost:8601/lib.min.js:203817:12)    at PaperCanvas.wrapper [as switchCostume] (http://localhost:8601/lib.min.js:89274:15)    at PaperCanvas.componentWillReceiveProps (http://localhost:8601/lib.min.js:203743:14)Component stack:     in PaperCanvas (created by Connect(PaperCanvas))    in Connect(PaperCanvas) (created by PaintEditorComponent)    in div (created by ScrollableCanvasComponent)    in ScrollableCanvasComponent (created by ScrollableCanvas)    in ScrollableCanvas (created by Connect(ScrollableCanvas))    in Connect(ScrollableCanvas) (created by PaintEditorComponent)    in div (created by PaintEditorComponent)    in div (created by PaintEditorComponent)    in div (created by PaintEditorComponent)    in PaintEditorComponent (created by InjectIntl(PaintEditorComponent))    in InjectIntl(PaintEditorComponent) (created by PaintEditor)    in PaintEditor (created by Connect(PaintEditor))    in Connect(PaintEditor) (created by KeyboardShortcutsWrapper)    in KeyboardShortcutsWrapper (created by Connect(KeyboardShortcutsWrapper))    in Connect(KeyboardShortcutsWrapper) (created by CopyPasteWrapper)    in CopyPasteWrapper (created by Connect(CopyPasteWrapper))    in Connect(CopyPasteWrapper) (created by UndoWrapper)    in UndoWrapper (created by Connect(UndoWrapper))    in Connect(UndoWrapper) (created by SelectionComponent)    in SelectionComponent (created by Connect(SelectionComponent))    in Connect(SelectionComponent) (created by UpdateImageWrapper)    in UpdateImageWrapper (created by Connect(UpdateImageWrapper))    in Connect(UpdateImageWrapper) (created by PaintEditorWrapper)    in PaintEditorWrapper (created by Connect(PaintEditorWrapper))    in Connect(PaintEditorWrapper) (created by CostumeTab)    in div (created by Box)    in Box (created by AssetPanel)    in div (created by Box)    in Box (created by AssetPanel)    in AssetPanel (created by CostumeTab)    in CostumeTab (created by Connect(CostumeTab))    in Connect(CostumeTab) (created by InjectIntl(Connect(CostumeTab)))    in InjectIntl(Connect(CostumeTab)) (created by ErrorBoundaryWrapper)    in ErrorBoundary (created by Connect(ErrorBoundary))    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)    in ErrorBoundaryWrapper (created by MediaQuery)    in div (created by TabPanel)    in TabPanel (created by MediaQuery)    in div (created by UncontrolledTabs)    in UncontrolledTabs (created by Tabs)    in Tabs (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in MediaQuery (created by GUIComponent)    in GUIComponent (created by Connect(GUIComponent))    in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))    in InjectIntl(Connect(GUIComponent)) (created by GUI)    in GUI (created by Connect(GUI))    in Connect(GUI) (created by InjectIntl(Connect(GUI)))    in InjectIntl(Connect(GUI)) (created by CloudManager)    in CloudManager (created by Connect(CloudManager))    in Connect(CloudManager) (created by VMManager)    in VMManager (created by Connect(VMManager))    in Connect(VMManager) (created by VMListener)    in VMListener (created by Connect(VMListener))    in Connect(VMListener) (created by ProjectSaverComponent)    in ProjectSaverComponent (created by Connect(ProjectSaverComponent))    in Connect(ProjectSaverComponent) (created by ProjectFetcherComponent)    in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))    in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))    in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)    in QueryParserComponent (created by Connect(QueryParserComponent))    in Connect(QueryParserComponent) (created by FontLoaderComponent)    in FontLoaderComponent (created by Connect(FontLoaderComponent))    in Connect(FontLoaderComponent) (created by ErrorBoundaryWrapper)    in ErrorBoundary (created by Connect(ErrorBoundary))    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)    in ErrorBoundaryWrapper (created by LocalizationWrapper)    in IntlProvider (created by Connect(IntlProvider))    in Connect(IntlProvider) (created by LocalizationWrapper)    in LocalizationWrapper (created by Connect(LocalizationWrapper))    in Connect(LocalizationWrapper) (created by TitledComponent)    in TitledComponent (created by HashParserComponent)    in HashParserComponent (created by Connect(HashParserComponent))    in Connect(HashParserComponent) (created by AppStateWrapper)    in IntlProvider (created by Connect(IntlProvider))    in Connect(IntlProvider) (created by AppStateWrapper)    in Provider (created by AppStateWrapper)    in AppStateWrapper

**Comment by fsih** [comment]
This is failing at https://github.com/LLK/paper.js/blob/develop/src/svg/SvgImport.js#L322

Paint expects all text it receives to be formatted in a series of tspans.
svg-renderer expects projects from Scratch 2.0 to have text elements that don't contain any tspan elements, and will convert the text to tspan elements in order to properly position text: https://github.com/LLK/scratch-svg-renderer/blob/ff98b880bc6f30ef8714fa0ca2b619c564c2a741/src/svg-renderer.js#L196

The issue with this particular SVG is that the text element contains both text outside of tspans and text inside of tspans, so the conditional doesn't get triggered. Paint then fails to parse because it sees text without a tspan during svg import
