### ISSUE TITLE
Crash in stretchy-paint branch

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#937]
- Go to costume tab
- Click on sprite library
- Add amon
- Switch back to costume tab

paper-full.js:15038 Uncaught Error: TypeError: Cannot read property 'getSize' of null
    at onError (paper-full.js:15038)
    at XMLHttpRequest.onLoad (paper-full.js:15029)
    at XMLHttpRequest.xhr.onload (paper-full.js:13688)
layer.js:37 Uncaught TypeError: Cannot read property 'removeChildren' of undefined
    at clearRaster (layer.js:37)
    at _makeRasterLayer (layer.js:164)
    at setupLayers (layer.js:262)
    at PaperCanvas.componentDidMount (paper-canvas.jsx:62)
    at commitLifeCycles (react-dom.development.js:8770)
    at commitAllLifeCycles (react-dom.development.js:9946)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at HTMLUnknownElement.dispatchEvent (<anonymous>)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
react-dom.development.js:9747 The above error occurred in the <PaperCanvas> component:
    in PaperCanvas
    in Connect(PaperCanvas)
    in div
    in ScrollableCanvasComponent
    in ScrollableCanvas
    in Connect(ScrollableCanvas)
    in div
    in div
    in div
    in PaintEditorComponent
    in InjectIntl(PaintEditorComponent)
    in PaintEditor
    in Connect(PaintEditor)
    in KeyboardShortcutsWrapper
    in Connect(KeyboardShortcutsWrapper)
    in CopyPasteWrapper
    in Connect(CopyPasteWrapper)
    in UndoWrapper
    in Connect(UndoWrapper)
    in SelectionComponent
    in Connect(SelectionComponent)
    in UpdateImageWrapper
    in Connect(UpdateImageWrapper) (created by PaintEditorWrapper)
    in PaintEditorWrapper (created by Connect(PaintEditorWrapper))
    in Connect(PaintEditorWrapper) (created by CostumeTab)
    in div (created by Box)
    in Box (created by AssetPanel)
    in div (created by Box)
    in Box (created by AssetPanel)
    in AssetPanel (created by CostumeTab)
    in CostumeTab (created by Connect(CostumeTab))
    in Connect(CostumeTab) (created by InjectIntl(Connect(CostumeTab)))
    in InjectIntl(Connect(CostumeTab)) (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by Connect(ErrorBoundary))
    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper (created by MediaQuery)
    in div (created by TabPanel)
    in TabPanel (created by MediaQuery)
    in div (created by UncontrolledTabs)
    in UncontrolledTabs (created by Tabs)
    in Tabs (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in MediaQuery (created by GUIComponent)
    in GUIComponent (created by Connect(GUIComponent))
    in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))
    in InjectIntl(Connect(GUIComponent)) (created by GUI)
    in GUI (created by Connect(GUI))
    in Connect(GUI) (created by InjectIntl(Connect(GUI)))
    in InjectIntl(Connect(GUI)) (created by CloudManager)
    in CloudManager (created by Connect(CloudManager))
    in Connect(CloudManager) (created by VMManager)
    in VMManager (created by Connect(VMManager))
    in Connect(VMManager) (created by VMListener)
    in VMListener (created by Connect(VMListener))
    in Connect(VMListener) (created by ProjectSaverComponent)
    in ProjectSaverComponent (created by Connect(ProjectSaverComponent))
    in Connect(ProjectSaverComponent) (created by TitledComponent)
    in TitledComponent (created by Connect(TitledComponent))
    in Connect(TitledComponent) (created by InjectIntl(Connect(TitledComponent)))
    in InjectIntl(Connect(TitledComponent)) (created by ProjectFetcherComponent)
    in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))
    in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))
    in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)
    in QueryParserComponent (created by Connect(QueryParserComponent))
    in Connect(QueryParserComponent) (created by FontLoaderComponent)
    in FontLoaderComponent (created by Connect(FontLoaderComponent))
    in Connect(FontLoaderComponent) (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by Connect(ErrorBoundary))
    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper (created by LocalizationWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by LocalizationWrapper)
    in LocalizationWrapper (created by Connect(LocalizationWrapper))
    in Connect(LocalizationWrapper) (created by HashParserComponent)
    in HashParserComponent (created by Connect(HashParserComponent))
    in Connect(HashParserComponent) (created by AppStateWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by AppStateWrapper)
    in Provider (created by AppStateWrapper)
    in AppStateWrapper

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:9747
minilog.js:17 gui Unhandled Error: TypeError: Cannot read property 'removeChildren' of undefined    at clearRaster (https://fsih.github.io/scratch-gui/stretchy-paint/lib.min.js:251123:9)    at _makeRasterLayer (https://fsih.github.io/scratch-gui/stretchy-paint/lib.min.js:251267:3)    at setupLayers (https://fsih.github.io/scratch-gui/stretchy-paint/lib.min.js:251372:3)    at PaperCanvas.componentDidMount (https://fsih.github.io/scratch-gui/stretchy-paint/lib.min.js:245274:73)    at commitLifeCycles (https://fsih.github.io/scratch-gui/stretchy-paint/lib.min.js:87835:24)    at commitAllLifeCycles (https://fsih.github.io/scratch-gui/stretchy-paint/lib.min.js:89011:9)    at HTMLUnknownElement.callCallback (https://fsih.github.io/scratch-gui/stretchy-paint/lib.min.js:79607:14)    at HTMLUnknownElement.dispatchEvent (<anonymous>)    at Object.invokeGuardedCallbackDev (https://fsih.github.io/scratch-gui/stretchy-paint/lib.min.js:79646:16)    at invokeGuardedCallback (https://fsih.github.io/scratch-gui/stretchy-paint/lib.min.js:79503:27)Component stack:     in PaperCanvas    in Connect(PaperCanvas)    in div    in ScrollableCanvasComponent    in ScrollableCanvas    in Connect(ScrollableCanvas)    in div    in div    in div    in PaintEditorComponent    in InjectIntl(PaintEditorComponent)    in PaintEditor    in Connect(PaintEditor)    in KeyboardShortcutsWrapper    in Connect(KeyboardShortcutsWrapper)    in CopyPasteWrapper    in Connect(CopyPasteWrapper)    in UndoWrapper    in Connect(UndoWrapper)    in SelectionComponent    in Connect(SelectionComponent)    in UpdateImageWrapper    in Connect(UpdateImageWrapper) (created by PaintEditorWrapper)    in PaintEditorWrapper (created by Connect(PaintEditorWrapper))    in Connect(PaintEditorWrapper) (created by CostumeTab)    in div (created by Box)    in Box (created by AssetPanel)    in div (created by Box)    in Box (created by AssetPanel)    in AssetPanel (created by CostumeTab)    in CostumeTab (created by Connect(CostumeTab))    in Connect(CostumeTab) (created by InjectIntl(Connect(CostumeTab)))    in InjectIntl(Connect(CostumeTab)) (created by ErrorBoundaryWrapper)    in ErrorBoundary (created by Connect(ErrorBoundary))    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)    in ErrorBoundaryWrapper (created by MediaQuery)    in div (created by TabPanel)    in TabPanel (created by MediaQuery)    in div (created by UncontrolledTabs)    in UncontrolledTabs (created by Tabs)    in Tabs (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in MediaQuery (created by GUIComponent)    in GUIComponent (created by Connect(GUIComponent))    in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))    in InjectIntl(Connect(GUIComponent)) (created by GUI)    in GUI (created by Connect(GUI))    in Connect(GUI) (created by InjectIntl(Connect(GUI)))    in InjectIntl(Connect(GUI)) (created by CloudManager)    in CloudManager (created by Connect(CloudManager))    in Connect(CloudManager) (created by VMManager)    in VMManager (created by Connect(VMManager))    in Connect(VMManager) (created by VMListener)    in VMListener (created by Connect(VMListener))    in Connect(VMListener) (created by ProjectSaverComponent)    in ProjectSaverComponent (created by Connect(ProjectSaverComponent))    in Connect(ProjectSaverComponent) (created by TitledComponent)    in TitledComponent (created by Connect(TitledComponent))    in Connect(TitledComponent) (created by InjectIntl(Connect(TitledComponent)))    in InjectIntl(Connect(TitledComponent)) (created by ProjectFetcherComponent)    in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))    in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))    in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)    in QueryParserComponent (created by Connect(QueryParserComponent))    in Connect(QueryParserComponent) (created by FontLoaderComponent)    in FontLoaderComponent (created by Connect(FontLoaderComponent))    in Connect(FontLoaderComponent) (created by ErrorBoundaryWrapper)    in ErrorBoundary (created by Connect(ErrorBoundary))    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)    in ErrorBoundaryWrapper (created by LocalizationWrapper)    in IntlProvider (created by Connect(IntlProvider))    in Connect(IntlProvider) (created by LocalizationWrapper)    in LocalizationWrapper (created by Connect(LocalizationWrapper))    in Connect(LocalizationWrapper) (created by HashParserComponent)    in HashParserComponent (created by Connect(HashParserComponent))    in Connect(HashParserComponent) (created by AppStateWrapper)    in IntlProvider (created by Connect(IntlProvider))    in Connect(IntlProvider) (created by AppStateWrapper)    in Provider (created by AppStateWrapper)    in AppStateWrapper
./node_modules/minilog/lib/web/formatters/minilog.js.logger.write @ minilog.js:17
paper-full.js:15038 Uncaught Error: TypeError: Cannot read property 'getSize' of null
    at onError (paper-full.js:15038)
    at XMLHttpRequest.onLoad (paper-full.js:15029)
    at XMLHttpRequest.xhr.onload (paper-full.js:13688)

**Comment by fsih** [comment]
The error is in the response to paper.project.importSVG(selectionAnchorIcon, ...) in the BoundingBoxTool constructor when the paint editor is getting initialized.

**Comment by fsih** [comment]
The issue is that paper.project.view is still null that early in the initialization process, so importSVG fails. The import needs to be moved later.

**Comment by fsih** [comment]
Moved to on mouse down
